services:
  attendance-app:
    image: attendance-management:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    env_file:
      - ../infra/env/.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: Asia/Tokyo
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Tokyo"
    volumes:
      - ../infra/lineworks:/app/keys/lineworks:ro
    networks:
      - local-app-network # 下で定義した外部ネットワークに参加

# 💡 外部ネットワーク（すでにdockerリポジトリ側で作られているもの）を使用する宣言
networks:
  local-app-network:
    external: true
