name: db-project

# compose.db.yaml
services:
  postgres:
    image: postgres:16-alpine
    container_name: shared-postgres
    ports:
      - "5432:5432"
    env_file:
      - ../infra/env/db/.env
    environment:
      - TZ=Asia/Tokyo
    networks:
      - local-app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # 💡 初回初期化スクリプトをマウント！
      - ../infra/env/db/init:/docker-entrypoint-initdb.d:ro

networks:
  local-app-network:
    name: local-app-network
    driver: bridge

volumes:
  postgres-data:
